import type { Metadata } from "next";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import { cn } from "@/lib/utils";
import { Header } from "./header";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme")?.value ?? "";

  return (
    <html lang="en">
      <body className={cn(geistSans.variable, geistMono.variable, "antialiased", theme)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
